meta:
  environment: (( param "please set environment" ))
  stemcell: (( param "please set environment" ))

name: (( grab meta.environment ))

director_uuid: (( param "please set environment" ))

releases: (( param "please set release" ))

networks: (( param "please set networks" ))

jobs: (( param "please set jobs" ))

properties: (( param "please set properties" ))

compilation:
  workers: 1
  network: influxdb-network
  reuse_compilation_vms: true
  cloud_properties: (( param "please set compilation cloud properties" ))

resource_pools:
  - name: influxdb-resource-pool
    network: influxdb-network
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please set resource_pool cloud properties" ))
